/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Continue": "继续",
    "You are a beautiful little planet, hanging out in a cosy little solar system": "你是一个美丽的小星球，生活在一个舒适的小太阳系里",
    "About": "关于",
    "Sound": "声音",
    "Music": "音乐",
    "Start over": "重新开始",
    "Import savegame": "导入存档",
    "Import Savegame": "导入存档",
    "Export savegame": "导出存档",
    "Back": "返回",
    "Impatient mode": "急躁模式",
    "Your surface": "您的表面",
    "Explore": "探索",
    "Space": "太空",
    "On your surface there are beautiful lush forests, and vast oceans. Unfortunately there is no life to enjoy the paradise": "在你的表面上有美丽茂盛的森林和浩瀚的海洋。不幸的是没有生命可以享受天堂",
    "Asteroid": "小行星",
    "There's something out there in the distance": "远处有什么东西",
    "Talk to the robot": "与机器人交谈",
    "Leave Burger on the asteroid": "把伯格留在小行星上",
    "Take Burger with you": "把伯格带走",
    "The robot seems happy to see you. It says that it was just enjoying the sunshine and that its name is Burger. It tells you that it can't remember much of anything since all of its memory was on a USB stick, and somehow it has gotten that USB stick misplaced. How unfortunate!": "机器人似乎很高兴见到你。它说它只是在享受阳光，它的名字叫伯格。它告诉你它什么都记不住，因为它所有的内存都在u盘上，不知怎么的，它把u盘放错了地方。多么不幸啊!",
    "You reach the huge potato-shaped chunk of asteroid. Nothing is there except for a small robot": "你到达了一个巨大的土豆形状的小行星。这里除了一个小机器人什么也没有",
    "Burger chirps happily as he softly lands on your surface.": "当伯格轻轻落在你的表面时，它高兴地叫着。",
    "Ok!": "好的!",
    "On your surface there are beautiful lush forests, and vast oceans. Burger is chirping through the forests": "在你的表面上有美丽茂盛的森林和浩瀚的海洋。伯格在森林里叽叽喳喳地叫着",
    "Shack you need to build before you can build everything else": "在你能建造其他东西之前，你需要建造一个小屋",
    "Talk to Burger": "和伯格交谈",
    "Workshop": "作坊",
    "Hello?": "哈喽？",
    "It's all totally dark here. Is anything here at all?": "这里一片漆黑。这里有什么东西吗?",
    "Wait, something is here!": "等等，这里有东西!",
    "Hey, look! A beautiful planet appeared": "嘿，看!一颗美丽的行星出现了",
    "BANG!": "砰！",
    "Is that you?": "那是你吗？",
    "That's pretty cool. Being a planet must be so exciting!": "太酷了。成为一颗行星一定很令人兴奋!",
    "You are so big and round and full of life": "你太大又圆，充满了生命",
    "But don't worry about it. There's probably plenty of life out in the universe": "不过别担心。宇宙中可能有很多生命",
    "Oh.. what's that? There's no life on your surface?": "哦. .那是什么?你的表面上没有生命吗?",
    "Build": "建造",
    "Well that figures. You were only just created in that big explosion before": "这是有道理的。你刚刚在之前的大爆炸中被创造出来",
    "Burger is happy to see you. It tells you that it can in fact be quite productive.\n What do you want burger to do?": "伯格很高兴见到你。它告诉你，它实际上可以非常高效。你想让伯格做什么?",
    "Chop wood": "砍木头",
    "Dig for gold": "开采黄金",
    "Hear secret": "聆听秘密",
    "Burger is chirping happily as it is getting to work": "伯格高兴地叫着，因为它要去工作了",
    "Right now Burger is chopping": "现在伯格砍伐",
    "In this workshop you can build anything! As long as it's one of the few options below": "在这个作坊里，你可以建造任何东西!只要它是下面几个选项之一",
    "Nimble axe": "灵动斧",
    "Upgrade": "升级",
    "Slot machine": "游戏机",
    "Don't know what to use your gold for? Now you can use your gold to win even more gold! If you are lucky you might even win some stardust": "不知道用你的黄金做什么?现在你可以用你的黄金赢得更多!如果幸运的话，你甚至可能赢得一些星尘",
    "Fragile gold drill": "脆弱的黄金钻头",
    "House for friends": "朋友之家",
    "If you want anybody living on you, they need some place to live": "如果你想让别人住在你身上，他们得有地方住",
    "BAM!": "砰!",
    "Axe upgraded!": "斧子已升级！",
    "Average axe": "平均斧",
    "Slightly luxurious axe": "略豪华的斧头",
    "You don't have any friends yet.. Sad. Very sad": "你还没有朋友…真悲哀。非常难过",
    "Friend house": "朋友之家",
    "You reach the huge potato-shaped chunk of asteroid. Nothing is there.. at all": "你到达了巨大的土豆形状的小行星。什么都没有……完全没有",
    "Psst! Burger is telling you a secret.\n The asteroid is actually a giant Coco Pops. What a revelation!": "嘘!伯格告诉你一个秘密。\n这颗小行星实际上是一个巨大的可可棒棒糖。这是什么启示啊!",
    "Hear news": "打听消息",
    "Show me": "给我看看",
    "Burger tells you that it has found a strange valley while working. It seems to be riddled with ancient dungeon entrances..": "伯格告诉你，它在工作时发现了一个奇怪的山谷。它似乎布满了古老的地牢入口…",
    "It's a valley full of dungeons. Leading into.. you? You'll need somebody to go down there, because you obviously can't": "这是一个充满地牢的山谷。通向……你?你需要有人去那里，因为显然你去不了",
    "Dungeons": "地牢",
    "Hear good news": "听好消息",
    "Right now Burger has a": "现在伯格有一个",
    "of mining": "开采",
    "Gold drill upgraded!": "黄金钻头已升级！",
    "Good enough gold drill": "足够好的黄金钻头",
    "Burger seems in a particularly good mood today. It shows you a handfuld of some glittery stuff.": "伯格今天看起来心情特别好。它向你展示了一些闪闪发光的东西。",
    "Burger tells you that it won it on the slot machine. You should give it a try!": "伯格告诉你它是在游戏机上赢的。你应该试试!",
    "Get the stardust!": "获取星尘！",
    "It's STARDUST!": "是星尘！",
    "Ka-ching!": "咔嚓!",
    "Very luxurious axe": "非常豪华的斧头",
    "Check it out": "去看看",
    "You see a small object in the distance. Is it a flying saucer? With a tiny gnome-like guy sitting in it? Smiling?": "你看到远处有一个小物体。它是一个飞碟吗?里面坐着个矮人似的家伙?微笑?",
    "Space Ben is sitting in his space shop.. Looking at you. Do you want to buy something? Do you?": "太空本坐在他的太空商店里。看着你。你想买什么东西吗?是吗?",
    "Starmap": "星图",
    "Green USB stick": "绿色U盘",
    "Orange USB stick": "橙色U盘",
    "Red USB stick": "红色U盘",
    "Perhaps it's full of secrets": "也许它充满了秘密",
    "Somebody drew with space ink on this old piece of paper.. It's supposed to show the way to someplace cool": "有人用太空墨水在这张旧纸上画画。它应该能指引我们去一个很酷的地方",
    "Buy": "购买",
    "Shop": "商店",
    "Oh yeah!": "哦，耶!",
    "You bought a very mystical starmap. Attempt to read it?": "你买了一张非常神秘的星图。试着阅读一下?",
    "You found a freezer floating in space!": "你发现了一个漂浮在太空中的冰箱!",
    "Yes!": "好！",
    "Are you sure you want to open the freezer? Really?": "你确定要打开冰箱吗?真的吗?",
    "OH BOY!": "哦，天哪!",
    "It's a furious bullman. Somebody clearly wanted this guy to cool it! He screams that his name is Derek, and that he is really cold and really pissed. However, he joins your space quest": "这是一个愤怒的牛头人。显然有人想让这家伙冷静下来!他尖叫着说他叫德里克，他很冷，很生气。然而，他加入了你的太空探索",
    "Derek's breathing heavily": "德里克呼吸沉重",
    "Equipment": "装备",
    "Talk": "交谈",
    "Derek is not wearing anything. How embarrassing!": "德里克什么都没穿。多尴尬啊!",
    "He bellows his thankfulness. He is indeed very happy that you let him beat up jerks. It's what he loves to do the most.": "他大声表示感谢。你让他揍混蛋，他确实很高兴。这是他最喜欢做的事。",
    "Talk more": "继续交谈",
    "Derek wipes away some spare froth from his mouth": "德里克擦去嘴里多余的泡沫",
    "Derek yells loudly while he practices some punches.": "德里克一边大声喊叫一边练习出拳。",
    "He explains, that he is allowed to go home only after beating the toughest most endless dungeon there is. Such a dungeon is said to exist in the belly of a monstrous creature.": "他解释说，只有在打败了最艰难、最无尽的地牢后，他才能回家。据说这样的地牢存在于一个怪物的肚子里。",
    "He grows tired of shouting, and with a calm voice he tells you about how he ended up in a freezer. It is custom for all young Derekulians to be sent out in the universe to prove their jerk handling skills.": "他厌倦了大喊大叫，然后用平静的声音告诉你他是如何被关进冷冻室的。对于所有年轻的德雷库利安人来说，被送到宇宙中去证明他们对付混蛋的能力是一种习惯。",
    "He shouts loudly, and starts to cry and shout at the same time? He misses his home world Derekulus X.": "他大声喊叫，同时又哭又喊。他想念他的故乡——德瑞库勒斯X。",
    "He stumbles over a log of wood, and gets embarrassed that you can't hide your laughter.": "他被一根木头绊倒了，因为你无法掩饰你的笑声而感到尴尬。",
    "Space Ben will conduct some research into making stronger health potion. For a reasonable price your potions will heal": "太空本将进行一些研究，以制作更强的健康药水。以合理的价格，你的药剂将恢复",
    ".. You have": ".. 你有",
    "Buy Chests": "购买宝箱",
    "Experimental Potion Research": "试验药剂的研究",
    "Health potion": "生命药水",
    "It heals like": "它可以恢复大约",
    "upgrade": "升级",
    "You found something very stupid looking": "你发现了一些看起来很蠢的东西",
    "Axe of all trades": "万金油之斧",
    "Derek's Dungeon School": "德里克地牢学校",
    "Want your Derek to get any better. Education is the only way to go!": "希望你的德里克能好起来。教育是唯一的出路!",
    "build": "建造",
    "Welcome to the School of Derek! That bull might look primitive, but you can teach him a few odd tricks": "欢迎来到德里克学校!那头公牛可能看起来很原始，但你可以教它一些奇怪的把戏",
    "Classroom": "教室",
    "Gym": "健身房",
    "Upgrade Derek's potion belt capacity, so he can carry": "升级德里克的魔药腰带容量，让他可以携带",
    "Upgrade Derek's strength to": "把德里克的力量升级到",
    "Upgrade Derek's health to": "把德里克的生命值升级到",
    ". A healthy Derek is a Derek that's still alive. You should know this by now": "． 健康的德里克才是活着的德里克。你现在应该知道了",
    ". He can throttle more jerks to their doom without getting hurt": "． 他可以掐死更多的混蛋而不受伤",
    "And I'm pretty tough! I have": "而且我很坚强!我有",
    "Bull Fart": "牛屁",
    "Door of Regret": "悔恨之门",
    "Hey man! Am I pumped or what!?": "嘿，伙计!我是不是太兴奋了?",
    "Look! I'm carrying": "看！我带了",
    "Make Derek STRONGER!": "让德里克更强大!",
    "More spacious potion belt": "更宽敞的药水腰带",
    "Pump Derek's health": "提升德里克的生命值",
    "potions. He is gonna need all that juice": "药水。他会需要那些果汁的",
    "Research SUCCESSFUL!": "研究成功！",
    "Where did Space Ben get all these chests from? You probably shouldn't ask": "太空本从哪弄来这些箱子的?你也许不应该问",
    "You reach the huge potato-shaped chunk of asteroid. No wait. It's actually a giant Coco Pops!": "你到达了一个巨大的土豆形状的小行星。不，等等。它实际上是一个巨大的可可棒棒糖!",
    "Automatic Swirly Straw": "自动旋涡吸管",
    "You reach the huge potato-shaped chunk of asteroid. No wait. It's actually a giant Coco Pops!\nYour automatic wooden straw is sucking out delicious coco at a rate of": "你到达了一个巨大的土豆形状的小行星。不，等等。它实际上是一个巨大的可可棒棒糖!你的自动木吸管正在吸出美味的可可，速度是",
    "Upgrade swirly straw": "升级旋涡吸管",
    ". Delightful!": "。太好了!",
    "Suck that coco!": "吮吸可可!",
    "Try your luck on the slot machine. You might win some gold. You might even win some stardust": "在游戏机上碰碰运气。你可能会赢得一些黄金。你甚至可能赢得一些星尘",
    "Play the slots": "玩游戏机",
    "You plug the USB stick into burgers face. He jolts and bobs with sweet memories: He used to own a big villa in a neighbouring galaxy. He had wife, kids and even a dog": "你把u盘插到伯格的脸上。他在甜蜜的回忆中摇摆不定:他曾经在邻近的星系拥有一座大别墅。他有妻子，孩子，甚至还有一条狗",
    "Get new friend": "结交新朋友",
    "Meet the dog": "结识狗子",
    "You meet burgers old dog. It's very sweaty. Burger tells you that they used to be best friends": "你见到了伯格的老狗。它很容易出汗。伯格告诉你,他们曾经是最好的朋友",
    "Sweatson": "汗森",
    "You have some friends!": "你有了一些朋友!",
    "Sweatson is sweating his ears off, but still finds time to dig": "汗森已经汗流浃背了，但仍找时间去挖掘",
    "for you": "给你",
    "Sweatson is sweating bullets.": "汗森是流汗的子弹。",
    "You remember something about that dogs can't sweat, and that's why they make that insanse panting noise. Somehow you don't believe that anymore.": "你记得狗不会出汗，所以它们才会发出疯狂的喘气声。不知怎么的，你不再相信了。",
    "He attempts to bark, but accidentally swallows some sweat": "他试图吠叫，但不小心吞下了一些汗水",
    "Pompous gold drill": "浮夸的黄金钻头",
    "My health is like": "我的生命值大约是",
    "Check out all that new health!": "看看这些所有的新生命值！",
    "strength": "力量",
    "Space for more potions!": "更多存放药水的空间!",
    "Derek is STRONG!": "德里克变强了!",
    "你把U盘插进伯格里。据他回忆，他嘟嘟唧唧地叫着:他还是个年轻的机器人时，曾在一家冰淇淋店和这个融化的家伙一起工作": "",
    "Meet Meltyface": "结识熔化脸",
    "Derek ate something rotten. Bull farts have been known to clear the room on more than one occasion": "德里克吃了腐烂的东西。众所周知，牛的屁不止一次能把房间弄得满地都是",
    "Thirsty": "口渴",
    "Cool!": "酷！",
    "Derek has nothing equipped here": "德里克这里什么装备都没有",
    "Cool Dungeon (abyssal)": "很酷的地牢(深渊)",
    "Burger advice": "伯格的建议",
    "Derek can't wait to go see what's down those dungeons. You better choose a dungeon soon. Derek is breathing heavily.": "德里克迫不及待地想去看看地牢里有什么。你最好快点选个地牢。德里克呼吸沉重。",
    "Juicy Dungeon (shallow)": "多汁的地牢(浅)",
    "Scary Dungeon (deep)": "可怕的地牢(深)",
    "Through chirps and beeps, he convinces you that it's best to start with the shallow dungeon. He talks a great deal about learning curves and Derek Safety Regulations.": "通过啾啾声和哔哔声，他说服你最好从浅层地牢开始。他讲了很多关于学习曲线和德里克安全规则的内容。",
    "You can tell that Burger knows a great deal about dungeons.": "你可以看出伯格对地牢非常了解。",
    "Honestly you get quite tired of listening after a while": "老实说，你听了一段时间就会感到厌倦",
    "More advice": "更多建议",
    "It's very embarrassing to enter the wrong door. Teach Derek to make a graceful exit, so he won't humiliate himself": "走错门是很尴尬的。教德里克优雅地退场，这样他就不会丢人了",
    "Derek does not yet know how to do this. You better teach him by buying this skill!": "德里克还不知道该怎么做。你最好买下这个技能来教他!",
    "Teach Derek to become so thirsty, that he will try to find health potions in desperation": "教德里克变得如此口渴，他会在绝望中寻找生命药水",
    "Skill upgraded!": "技能已升级！",
    "Burger carefully chirps a warning. It is important to have Derek properly educated before going into the dungeon. The poor bull might die, and it is said that only stardust will bring him back to life again.": "伯格小心翼翼地发出警告。在进入地牢之前，让德里克接受适当的教育是很重要的。可怜的公牛可能会死，据说只有星尘才能使他起死回生。",
    "Especially about doors in dungeons. He tells you that jerks typically like to hide behind doors of extra cool treasure. Like presents. He talks to lengths about jerk gravitational physics and treasure logic.": "特别是关于地下城的门。他告诉你，混蛋通常喜欢躲在特别酷的宝藏门后面。喜欢的礼物。他大谈特谈重力物理和宝藏逻辑。",
    "He chirps out some wisdom - The deeper you are in the dungeon, the more jerks you are going to see. He writes some simple, but mind boggling functions.": "他唧唧喳喳地说出了一些智慧——你在地牢里越深，你就会看到越多的混蛋。他编写了一些简单但令人难以置信的函数。",
    "He looks out in the distance. His slow chirps tell you that there must be more dungeons out in the universe. Much harder than these dungeons on your surface. You try to get Burger to tell you more, but something seems to be wrong with his memory parts again.": "他向远处望去。他缓慢的唧唧声告诉你，宇宙中肯定有更多的地牢。比你表面上的地下城难多了。你试图让伯格告诉你更多，但他的记忆部分似乎又出了问题。",
    "But he tells you that": "但是他告诉你在twitter上",
    "on twitter knows even more, and is just as eager to talk about dungeons.": "可以知道更多，他们也同样渴望谈论地牢。",
    "You enter the Juicy Dungeon": "你进入了多汁的地牢",
    "You enter the Scary Dungeon": "你进入了可怕的地牢",
    "You enter the Cool Dungeon": "你进入了很酷的地牢",
    "Let's go!": "出发！",
    "Leave this dungeon!": "离开地牢！",
    ". There are two doors. Which one will Derek enter?": "． 有两扇门。德里克会进入哪一个?",
    "Derek is on": "德里克当前是",
    "of this dungeon. Derek's health is like": "在当前地牢。德里克的生命值大约是",
    "Look at this. You won a small soft present": "看看这个。你赢得了一份小礼物",
    "Open": "打开",
    "GIFT EXPLOSION!!!": "礼物大爆炸!!",
    "Open it!": "打开它！",
    "Well well": "不错不错",
    "Score! A medium hard present for you": "得分!给你一个中硬的礼物",
    "Let's open this bad boy": "让我们打开这个坏小子",
    "You are the luckiest planet in the universe! You won a big massive present!": "你是宇宙中最幸运的星球!你赢得了一份大礼物!",
    "Open it damnit!": "该死的，快打开!",
    "We didn't win anything. How unfortunate!": "我们没有赢得任何东西。太不幸了!",
    "You slip in the melted ice cream on the floor.": "你滑倒在地板上融化的冰淇淋上。",
    "Meltyface": "熔化脸",
    "Meltyface doesn't seem to notice that he is melting": "融化脸似乎没有注意到自己正在融化",
    "Meltyface is melting his face off, while producing": "融化脸正在融化他的脸，同时生产",
    "Meltyface is dripping on you.": "融化的脸滴在你身上。",
    "You try to talk to Meltyface, but you can't hear anything over the constant dripping.": "你试着和熔化脸说话，但你听不到任何声音，因为不停地滴水。",
    "He tells you about the other night where Derek tried to eat his face off. But Derek slipped and fell.": "他告诉你那天晚上德里克想把自己的脸吃掉。但是德里克滑倒了。",
    "Mystery door": "神秘的门",
    "Small present door": "小礼物门",
    ". There's around": "。周围有",
    "So dude, this is": "伙计，这是",
    "Check Derek's equipment": "检查德里克的装备",
    "Fight them!": "攻击他们！",
    "in this room. I'm totally gonna wreck them by the way. Also my health is like": "在这个房间里。顺便说一句，我一定会毁了他们。我当前的生命值大约是",
    "right now, but I'm cool": "，但是我很酷",
    "Chest door": "宝箱之门",
    "Derek?": "德里克？",
    "HELP!": "救命!",
    "OH NO!": "哦，不！",
    "WHAT!?": "纳尼！？",
    "URGH!": "呃！",
    "Open Chest": "打开宝箱",
    "I'm so pumped! I beat up": "我太兴奋了!我打败了",
    "I fended off": "我挡住了",
    "The remaining jerks only dealt": "剩下的混蛋只对我造成了",
    "to me": "",
    "right now, but I'm cool.": "当前，但是我很酷。",
    "Cool": "酷",
    "It's": "这是",
    "'They have pockets full of sawdust'": "'他们的口袋里装满了锯末'",
    "The mystery door turns out to be a": "神秘的门原来是一扇",
    ". How mysterious!": "。多么神秘!",
    "Let's a go!": "出发！",
    "Are you sure you want to leave this dungeon? You'll have to start on level 1 next time you dive in": "你确定要离开这个地牢吗?下次你必须从1级开始",
    "Shortcut!": "捷径！",
    "Go deeper!": "前往深处！",
    "Open present": "打开礼物",
    "Ok, wow! It looks there is a present for you down here": "好的,哇!看起来下面有一件礼物是给你的",
    "Loot!": "战利品！",
    "There's": "这里是",
    "Good job Derek!": "干得好，德里克!",
    "lying around in the corner of the room. Derek frantically gathers it for you": "躺在房间的角落里。德里克疯狂地为你收集",
    "'Just a single green glove'": "'只是一只绿色手套'",
    "What is it Derek?": "那是什么，德里克？",
    "What fantastic treasure could be inside?": "里面会有什么神奇的宝藏呢?",
    "WHAO! Who's there!?": "哇哦!谁在那儿!?",
    "Hey boss! There's this weird dino kind of thing down here": "嘿,老板!这下面有个奇怪的恐龙",
    "Meet dino thing": "结识恐龙",
    "It's an ancient juicosaurus. It must have gotten stuck down here while all the dinos were busy getting extinct. He will make a great friend!": "这是一只古老的多汁龙。它一定是在所有恐龙忙于灭绝的时候被困在这里的。他会成为一个好朋友的!",
    "Juicosaurus went to your friend house. Go see what he is working o": "多汁龙去了你的朋友之家。去看看他在做什么",
    "Ok": "确定",
    "Stop shouting Derek!": "别喊了，德里克!",
    "Derek is shouting at you from the bottom of the dungeon. He is trying to tell you that there are no more levels of this dungeon..": "德里克在地牢里对你大喊大叫。他是想告诉你这个地下城没有更多的关卡了。",
    "Juicosaurus": "多汁龙",
    "Juicosaurus is spewing juice all over the place. That somehow gives you": "多汁龙的汁液喷得到处都是。这给了你",
    "He tells you about his fellow juicosauruses. It's amazing that they managed to get extinct so quickly after their world was created.": "他会告诉你他的多汁龙同伴。令人惊讶的是，在它们的世界被创造出来之后，它们就这么快灭绝了。",
    "Juicosaurus is making a gurgling roar.": "多汁龙在发出咯咯的吼声。",
    "There's juice everywhere": "到处都是果汁",
    "He fends off a wild crowd of archaeologists.": "他击退了一群疯狂的考古学家。",
    "This is the story of how he stumbled on a dungeon, and fell down in it. The jerks down there took care of him and raised him as their own.. In a jerkly fashion of course.": "这个故事讲的是他如何偶然发现了一个地牢，并在里面摔倒了。那里的混蛋照顾他，把他当自己的孩子养大。当然是以一种突然的方式。",
    "He explains that jerks aren't actually that bad. Derek punches him hard in the face before he can finish the sentence.": "他解释说，混蛋其实没那么坏。德里克还没等他说完话，就狠狠地打了他一拳。",
    "Shoot! So close": "该死!如此接近",
    "Some of this equipment is smelling weird": "有些装备闻起来怪怪的",
    "Look! It's": "看！那是",
    "Equip": "装备",
    "Fits perfectly!": "非常适合!",
    "Unequip": "脱下",
    "Scary news": "可怕的消息",
    "Despite Dereks huge thirst, he didn't find anything tasty to drink. A dry mouth can be fatal!": "尽管德里克非常口渴，但他没有找到任何可口的饮料。口干是致命的!",
    "Derek really didn't like what was behind that door. The regret is so thick you could cut through it. But you probably don't want to. You want to pick another door instead": "德里克真的不喜欢那扇门后面的东西。悔恨之情如此强烈，你甚至可以把它切开。但你可能不想这么做。你想选择另一扇门",
    "Sure": "确定",
    "Derek farts. It stinks! All the jerks died instantly..": "德里克放了个屁。它真的很臭!所有的混蛋都被当场熏死了…",
    "Cool! But also smelly": "太酷了!但也很臭",
    "Medium present door": "中礼物之门",
    "Big present door": "大礼物之门",
    "DEREK!?": "德里克！？",
    "I can't afford it": "我买不起",
    "Looks like the Jerks got Derek. Use": "看来德里克被混蛋抓住了。使用",
    "to revive him?": "去复活他?",
    "He tries to fetch something for you, but is too exhausted, and takes a shower instead.": "他想给你拿点东西，但他太累了，于是去洗澡了。",
    "You realize that he's a talking dog, but he talks in a language that you don't understand. Typically!": "你意识到他是一只会说话的狗，但他说的语言你听不懂。很典型!",
    "He says: Jeg har det simpelthen bare så varmt. Kan du ikke hente en klud til mig? You don't get a word of it.": "他说：“我很高兴见到你。”。你能一直呆到现在吗？你对此一无所知。",
    "He says: Jeg spiste engang en hel skål slik. Det smagte af pandekager. You pet him and pretend you understand.": "他说：Jeg spiste eng en hel skål slik。这是一种迎合。你抚摸他，假装你理解。",
    "He says: Hey skipper! Stikker du mig ikke en kold bajer? Jeg kunne dælme også godt spise en is nu hvor du er i gang. You wonder if he is a talking dog, or he is just making strange noises?": "他说：嘿，船长！你想和巴杰一起玩吗？我的上帝保佑你们。你想知道它是会说话的狗，还是只是发出奇怪的声音？",
    "He says: Lort i lommen er bedre end ost med kommen. You are sure that those were wise words.": "他说：“上帝保佑我们，上帝保佑我们。”。你肯定这些话很明智。",
    "He says: Årh, jeg glæder mig til at komme i byen i aften. You have an urge to ask him why, but you don't want to start an argument.": "他说：啊，我会一直到最后。你很想问他为什么，但你不想挑起争端。",
    "Can I help you? Can I?": "我能帮助你吗？我可以吗？",
    "Derek is finally wearing something! He gets all these advantages:": "德里克终于有衣服穿了!他拥有所有这些优势:",
    "Derek is wearing": "德里克穿上了",
    "Save Derek!": "拯救德里克！",
    "There there Derek..": "好了，好了，德里克…",
    "'This guy is eager to chop some wood'": "'这家伙很想砍柴'",
    "Stardust door": "星尘之门",
    "'These glasses are desperately looking for something to drink'": "'这些眼镜正在拼命寻找一些喝的'",
    "'Might as well do some light exercise while punching jerks'": "'在打混蛋的时候，不妨做一些轻微的运动'",
    "Much better!": "好多了！",
    "REFRESHING!! Now my health is more like": "清爽!!现在我的生命值大概是",
    "'This golden fist looks like it was worn by an ancient hero without arms and legs'": "'这只金拳头看起来像是古代一位没有胳膊和腿的英雄佩戴的'",
    "Boss! Something scary is down here": "老板!下面有可怕的东西",
    "Pull yourself together!": "Pull yourself together!",
    "HOLY SMOKES! I just saw a real ghost!": "天啊!我刚刚看到了一个真正的幽灵!",
    "Meet the ghost": "结识幽灵",
    "It's super creepy, but you think you can become friends with this ghost. Besides, it smells of sweet coco": "虽然超级恐怖，但你觉得你可以和这个幽灵成为朋友。此外，它闻起来有甜可可的味道",
    "Coco ghost went to your friend house. Go see what he is working on": "可可幽灵去了你朋友之家。去看看他在做什么",
    "Coco ghost": "可可幽灵",
    "Coco ghost is floating around in a coco haze. That produces": "可可幽灵漂浮在可可的薄雾中。生产",
    "He makes you a warm cup of coffee.": "他给你煮了一杯热咖啡。",
    "He passes through a wall just to make a point": "他穿过一堵墙只是为了表达一个观点",
    "You are feeling a cold chill in Coco ghosts presence.": "你在可可鬼魂的存在中感到一阵寒意。",
    "There's a red dot in the distance": "远处有个红点",
    "It seems to be an apple.. There's something special about it. There's also a hole in it": "它似乎是一个苹果……它有一些特别之处。上面还有一个洞",
    "Knock on the apple": "敲苹果",
    "Go away mortal! I'm not interested in meeting you. Not unless you are popular": "走开，凡人!我没兴趣见你。除非你很受欢迎",
    "Oh, a planet. What a pleasant surprise": "哦，一颗行星。真是个惊喜",
    "Nice to meet you": "很高兴见到你",
    "Likewise. I am Remouladin the almighty Worm God. I see you are already moderately populated - well on your way to becoming a decent planet": "我也是。我是雷穆拉丁，全能的虫神。我看到你已经有了适度的人口——正在成为一个体面的星球",
    "Thank you Remouladin": "谢谢你，雷穆拉丁",
    "I'll be back!": "我会回来的!",
    "So, planet. I think we might be able to work out a deal.. If you get 6 friends to live on you, then I will help you on your quest": "所以，行星。我想我们也许能达成一笔交易。如果你有6个朋友住在你身上，那么我会帮助你完成你的任务",
    "Worm god": "虫神",
    "Aah, planet. How's the socializing going? Did you get 6 friends yet?": "啊，行星。社交活动进行得怎么样了?你有6个朋友了吗?",
    "Actually he was sent here to haunt you, but he seems to have forgotten why, so now you are getting along just fine.": "实际上他是被派来缠着你的，但他似乎已经忘记了为什么，所以现在你们相处得很好。",
    "You play a game of Crazy Eights, while eating some biscuits.": "你一边吃着饼干，一边玩“Git游戏”。",
    "He tells you about life in the dungeons.. It was great! But his holiday visa ran out, so he had to leave.": "他告诉你地牢里的生活。太棒了!但是他的假期签证到期了，所以他不得不离开。",
    "So many potions in that belt!": "腰带里有好多药水!",
    "John": "约翰",
    "Meet John": "结识约翰",
    "Burger swallows the USB stick whole, and jumps around with his hands in the air. His lost memories spill like beans: When he got divorced, he hitched a ride with this creepy fellow, John": "伯格一口吞下了u盘，双手在空中跳来跳去。他失去的记忆如影随形:当他离婚时，他搭了一个叫约翰的怪人的便车",
    "You meet John. He will haunt your dreams.. But besides from that he will probably make a great friend": "你结识了约翰。他会在你梦中出没……但除此之外，他可能会交到一个好朋友",
    "John went to your friend house. Go see what he is working on": "约翰去你朋友之家了。去看看他在做什么",
    "John is haunting your dreams. He also gives you": "约翰在你的梦中作祟。他也给了你",
    "Through a scary vision he shows you a flash from his past. He used to work as a travelling salesman.. He used to be pretty good at that.": "通过一个可怕的幻象，他向你展示了他过去的一闪。他过去做过旅行推销员。他以前很擅长这个。",
    "You try not to stare directly at John.": "你尽量不要直视约翰。",
    "You are too unnerved to continue the conversation": "你太紧张了，无法继续谈话",
    "He tells you that he used to work in this co-working space, but got thrown out because he was on the phone constantly. He knows that the real reason why, is that he was haunting everybody's dreams.": "他告诉你，他曾经在这个联合办公空间工作，但被赶了出去，因为他一直在打电话。他知道真正的原因是，他在每个人的梦里徘徊。",
    "He went to school with this Stupid Looking Planet, who was quite shy. They hung out quite a bit then, but lost touch after school.": "他和一个很害羞的“愚蠢星球”同学一起上学。那时他们经常在一起玩，但放学后就失去了联系。",
    "'Mmmh.. Coco!'": "'嗯.. 可可!'",
    "Let's a go go!": "我们走吧!",
    "'It's surprisingly solid'": "'它出奇地坚固'",
    "Uuuf! I feel a cool chill": "哎哟!我感到一阵凉意",
    "Get a grip and tell me what's going on": "冷静点，告诉我发生了什么事",
    "Hey! I found some sort of jerk. But I don't think it's a real jerk though": "嘿!我找到了一个混蛋。但我不认为这是一个真正的混蛋",
    "Meet fake jerk": "结识假混蛋",
    "It's Kim Cumber! The legendary dungeon crawler. You can't believe that he will be your friend": "我是金·康伯!传说中的地下城爬行者。你不会相信他会成为你的朋友",
    "Kim Cumber went to your friend house. Go see what he is working on": "金·康伯去了你的朋友之家。去看看他在做什么",
    "Kim Cumber": "金·康伯",
    "Kim cumber is cool as a cucumber. His words turn into": "金·康伯很酷。他的话变成了",
    "You are afraid of making a fool of yourself in front of Kim.": "你害怕在金面前出丑。",
    "Kim peels some skin off for his G&T": "金为他的杜松子酒剥了一些皮",
    "He tells you something amazing about himself, without even bragging. He's so cool!": "他会告诉你一些关于他自己的惊人的事情，甚至不自夸。他太酷了!",
    "I have 6 friends!": "我有6个朋友了！",
    "Well done planet. You have proven yourself worthy... Are you ready to witness the true power of Remouladin?": "干得好，行星。你已经证明了自己的价值……你准备好见证雷穆拉丁的真正力量了吗?",
    "Behold! The power of Remouladin": "看哪!雷穆拉丁的力量",
    "Enter wormhole": "进入虫洞",
    "Now, enter the wormhole planet": "现在，进入虫洞星球",
    "WOAAH!": "哇！",
    "It looks like you have arrived right next to a giant space broccoli. What a marvelous sight!": "看起来你就在一个巨大的太空西兰花旁边。多么奇妙的景象啊!",
    "Amazing! There is a whole world on the surface of the broccoli. Is that Loch Juice? And over there - a castle made entirely of coco. Oh, and could that be the fabled Tall Blue Forest there in the distance?": "神奇的!西兰花的表面上有一个完整的世界。那是洛克果汁吗?那边是一座完全由可可制成的城堡。哦，难道远处就是传说中的高大的蓝色森林吗?",
    "We have to discover this new world!": "我们必须发现这个新世界!",
    "Take a closer look": "仔细看看",
    "You can hear Burger chirping nervously. Maybe he is freaking out about this broccoli place.. He tells you that you just left the coco asteroid and Stupid Looking Planet behind. But you can tell that there is also something else nagging him": "你可以听到伯格紧张的唧唧声。也许他被这个花椰菜店吓坏了…他告诉你，你刚刚离开了可可小行星和愚蠢的星球。但是你可以看出还有别的事情在困扰着他",
    "Don't worry Burger!": "别担心，伯格！",
    "You feel like something is missing, but you are not quite sure what": "你觉得少了什么，但又不确定是什么",
    "Hmm..": "嗯..",
    "Blue Forest": "蓝色森林",
    "Coco Castle": "可可城堡",
    "Loch Juice": "洛克果汁",
    "It smells like farts here, but I don't know what else you would expect from a broccoli world": "这里闻起来像屁，但我不知道你还能从西兰花的世界里期待什么",
    "You wonder if a planet has ever been in a forest before, but you try not to worry too much about it. In the distance is a huge villa, and a small shack": "你想知道以前是否有行星进入过森林，但你尽量不太担心。远处是一座巨大的别墅和一个小棚屋",
    "Big Villa": "大别墅",
    "Little shack": "小木屋",
    "You enter the melty halls of the Coco Castle. On the throne sits Empress Cocobar of the Broccoli Empire. You pay a bunch of respect and she asks what's up": "你进入可可城堡融化的大厅。王位上坐着椰菜帝国的可可巴皇后。你很尊重她，她问你怎么了",
    "What's up yourself?": "你怎么了?",
    "Coco Penguin?": "可可企鹅？",
    "Can I use your phone?": "我可以用一下你的电话吗?",
    "You finally build the courage to ask about the giant Coco Penguin in the corner. The Empress doesn't seem to care, so knock yourself out I guess": "你终于鼓起勇气去问角落里那只巨大的可可企鹅。皇后似乎并不在乎，所以我想请自便吧",
    "Thanks!": "谢谢!",
    "Broccoli Empire": "西兰花帝国",
    "A small figure emerges from the shack. Sven tells you how sorry he is that he cut down so many trees. He complains about a conflict between his own nature, as a chainsaw, and ethics": "一个小身影从棚屋里出现。斯文告诉你，他很抱歉砍了那么多树。他抱怨自己像电锯一样的本性与道德之间的冲突",
    "It's fine Sven": "没关系，斯文",
    "Be ashamed beast!": "羞愧吧，野兽!",
    "Check it out!": "查看一下！",
    "Sven finds comfort in your comforting words. He gives you a pamphlet of possible upgrades that can be made to his woodcutting performance. The paper quality of the brochure is divine. The graphic design could use some work": "斯文从你安慰的话语中得到安慰。他给了你一本小册子，上面写着他的木刻技术可以改进的地方。这本小册子的纸张质量非常好。平面设计还有待改进",
    "Summons a powerful DM that can help you come up with endless jerk-riddled dungeons": "召唤一个强大的 地下城主，可以帮助你创造无尽的地牢",
    "Dungeon Master": "地下城主",
    "Summon": "召唤",
    "Creates the longest dungeon ever": "创造有史以来最长的地牢",
    "Let's play some Dungeons & Dereks!": "让我们一起来玩《地牢与德里克》吧!",
    "The floating face of the mighty DM is hanging in the air. Let's come up with some new dungeons for this campaign!": "强大的地下城主的浮脸悬在空中。让我们为这个战役设计一些新的地下城吧!",
    "Creates the longest dungeon ever": "",
    "Endless Dungeon": "无尽的地牢",
    "It's endless!!": "它是无尽的！",
    "You enter the Endless Dungeon": "你进入了无尽的地牢",
    "I blocked off": "我格挡了",
    "You reach the shore of a juicy lake. In the middle is a giant purple sea creature": "你来到了一个多汁的湖边。中间是一个巨大的紫色海洋生物",
    "It will remove all your progress in your current savegame": "它将覆盖你当前保存的所有游戏进度",
    "Are you sure you want to import a savegame from a .planet file?": "您确定要从.planet文件导入存档吗?",
    "You are a shiny little mechanical planet, hanging out in a remote solar system": "你是一颗闪亮的机械小行星，游荡在遥远的太阳系",
    "Beanie": "比尼",
    "Space Bar": "",
    "Ancient Planet": "远古行星",
    "Stanley The Star": "斯坦利星",
    "Space Bar": "太空酒吧",
    "Your Surface": "你的表面",
    "What's up?": "怎么了?",
    "Burger congratulates you with beating all three dungeons. He gives you a friendly chirp on the back, and suggests that you go see what's up in the workshop": "伯格祝贺你打败了三个地牢。他在你背后友好地叫了一声，建议你去看看作坊里发生了什么",
    "Why don't you go take a look?": "你为什么不去看看呢?",
    "Why don't you go take a look around?": "你为什么不四处看看呢?",
    "Beanie is spinning around herself in a very graceful way": "比尼以一种非常优雅的方式旋转着自己",
    "Stanley is getting a little dizzy seeing the whole solar system spinning around him. Then he giggles and everything is fine.": "斯坦利看到整个太阳系在他周围旋转，有点头晕。然后他咯咯地笑，一切都好了。",
    "He has gathered": "他收集了",
    "Thanks Stanley!": "谢谢你，斯坦利！",
    "Stanley hands you": "斯坦利递给你",
    "He laughs with joy. Nothing makes him happier than helping out his friends": "他高兴地笑了。没有什么比帮助朋友更让他高兴的了",
    "There's an ancient planet floating about. It's been dead for a long time now.": "有一颗古老的行星漂浮着。它已经死了很长时间了。",
    "On its surface there is a small fenced garden, and the entrance to a dungeon": "在它的表面上有一个用篱笆围起来的小花园和一个地牢的入口",
    "The Garden Boys": "花园男孩",
    "Examine Dungeon": "检查地牢",
    "The Garden Boys are trying to look innocent. Do you want to hire one of them for a some sneaky spelunking?": "花园少年试图装出无辜的样子。你想雇他们中的一个来做一些秘密的洞穴探索吗?",
    "Lil' Gnomey's brags about having reached": "小矮人吹嘘自己已经到达",
    "The gnome puts on his sneaky shoes. The dungeon awaits.": "矮人穿上了他那双鬼鬼祟祟的鞋子。地牢在等着你。",
    "Don't wake up any Derekulians!": "别吵醒任何德雷库尔人!",
    "You take a peek down the dungeon. Dungeons like these used to be filled with jerks, but a dead planet can't sustain any jerks. Now all you can hear from the depths are the bored howls of old Derekulians.": "你往地牢里看了一眼。像这样的地下城过去充满了混蛋，但一个死亡的星球无法承受任何混蛋。现在你能从深处听到的只有老德雷库利安人无聊的嚎叫。",
    "There could still be treasure down there.. If only you had somebody who could sneak down there, without getting noticed by the bored bulls": "下面可能还有宝藏……要是有人能偷偷溜过去，不被那些无聊的公牛发现就好了",
    "Your gnome is on": "你的矮人当前是地牢",
    "of the dungeon.": "。",
    "There are two doors. Which one should the gnome enter?": "有两扇门。矮人应该进入哪一个?",
    "There's an ancient party going on in there.. You are unsure if anybody even enjoys it anymore.": "那里正在举行一场古老的派对。你不确定是否还有人喜欢它。",
    "But you are here to sell your coco, so stop worrying about that.": "但你是来卖可可的，所以别再担心了。",
    "You have left around": "你留下了",
    "at the bar. They earn": "在酒吧。它们赚取",
    "every 10 seconds!": "每10秒！",
    "How does this work?": "这是如何工作的呢?",
    "It's easier to sell to happy customers. Will give you more gold every 10 seconds": "这样更容易把产品卖给满意的客户。每10秒会给你更多的黄金",
    "Deposit coco": "放入可可",
    "Buy a round of drinks": "请大家喝一杯",
    "Sounds legit": "听起来很合理",
    "Hey don't worry about it. These guys got you covered.": "嘿，别担心。这些人会掩护你的。",
    "If you just leave your coco here, they will turn it around in no time. That means gold!": "如果你把可可留在这里，他们很快就会把它翻过来。那意味着黄金!",
    "The more coco deposited, the quicker it will be flipped": "可可堆积得越多，翻转得就越快",
    "You've deposited": "你放入了",
    "at the bar. The dealers are hard at work, converting it to gold for you. Just don't ask any questions": "在酒吧。交易商在努力工作，把它兑换成黄金。不要问任何问题",
    "You pick up": "你拿起",
    "from the dealers. You casually threaten them, so they can keep up their excellent work": "从经销商那里。你不经意地威胁他们，让他们继续出色的工作",
    "Better not be skimmin' on me boys!": "孩子们，你最好别偷我的钱!",
    "Your fragmented mechanical surface is creaking and clonking. Deep chirps come from within your robot core": "你那破碎的机械表面在吱吱作响。低沉的唧唧声来自你的机器人核心",
    "Your Core": "你的核心",
    "Wood Synthesizer": "木头合成器",
    "Bret": "布雷特",
    "Celestial Summoner": "天体召唤师",
    "Your core is warm and glowing. There is": "你的核心是温暖的，发光的。有",
    "flowing in there": "在那里流动",
    "Harvest core": "收获核心",
    "Beanies Beanshop": "比尼的豆子店",
    "Baby engineer": "婴儿工程师",
    "in your core. Do you want to take it out and just put it in your wallet somehow?": "在你的核心。你想把它拿出来放在钱包里吗?",
    "There is": "这里有",
    "The baby drools on a floor plan of your innards. It points to some upgrades it can make to your inner dungeon": "婴儿在你内脏的平面图上流口水。它指出了可以在你的内部地牢中进行一些升级",
    "Stardust Capacity": "星尘容量",
    "Interesting": "有点意思",
    "In very simple language, the baby explains that you can pull out all the stardust from your core, if you ever need some stardust to spend": "宝宝用非常简单的语言解释说，如果你需要一些星尘，你可以从你的核心抽出所有的星尘",
    "The baby gurgles": "婴儿咯咯地笑",
    "The baby shows you some sketches of how your core works. If you feed it beans that are the same color as the core it will generate more stardust": "婴儿向你展示了一些你的核心是如何工作的草图。如果你给它喂食和核心颜色相同的豆子，它就会产生更多的星尘",
    "The baby starts to cry": "婴儿开始哭了",
    "Space Ben": "太空本",
    "Villa": "别墅",
    "Scary!!": "可怕! !",
    "Buy answers": "购买答案",
    "Space Ben is sitting in his space shop.. Looking at you. Do you want to buy something? Do you? You have": "本正坐在他的太空商店里。看着你。你想买点什么吗?是吗?你有",
    "ghosts": "幽灵",
    "Space Ben has the answers you seek. So buy them!": "太空本有你想要的答案。那就买吧!",
    "An answer costs": "一个答案消耗",
    "ghost(s). You have": "幽灵。你有",
    "Planet": "星球",
    "Remouladin": "雷穆拉丁",
    "Coco": "可可",
    "Burger": "伯格",
    "Broccoli": "西蓝花",
    "Jerks": "混蛋",
    "Stardust": "星尘",
    "Coco Dungeons": "可可地牢",
    "Coco Penguin!": "可可企鹅！",
    "Cocobar is looking at you sceptically. She reminds you that there are still jerks in her coco dungeons, so is there even time for talking?": "可可巴怀疑地看着你。她提醒你她的可可地牢里还有混蛋，所以还有时间说话吗?",
    "Cool it": "冷静下来",
    "A gigantic penguin made out of coco is now supplying you with": "一只由可可制成的巨大企鹅正在为你提供",
    "Build Automatic Swirly Straw": "建造自动旋涡吸管",
    "The Automatic Swirly Straw will suck": "自动旋涡吸管会吸取",
    "coco/sec out of that penguin": "可可/秒 从那只企鹅",
    "The entrances to the coco dungeons loom in the dim light. Derek is slightly distracted by the scent of coco, but you know he will focus once jerks are near": "可可地下城的入口隐约出现在昏暗的灯光下。德里克被可可的气味分散了注意力，但你知道只要有混蛋靠近，他就会集中注意力",
    "Melting Coco Dungeon (abyssal)": "融化的可可地牢 (深渊)",
    "DEREK!": "德里克!",
    "Is there?": "是吗?",
    "Cocobar is looking slightly less sceptically at you today. You are totally lucky to get some phone time! You have": "可可巴今天看你的眼神不那么怀疑了。你能有打电话的时间真是太幸运了!你有",
    "and": "和",
    "A shining phone coin for the space phone": "用于太空电话的闪亮电话金币",
    "Full Heal": "满血",
    "Derek uses his musky willpower to become super healthy!": "德里克用他的麝香意志力变得超级健康!",
    "'Worn by the primitive jerks of the past'": "'过去那些原始的混蛋穿的'",
    "Burg3r is happy to see you. But you don't care about that. You just want your Burger back! Maybe he is somewhere on that giant broccoli": "Burg3r很高兴见到你。但你不关心这个。你只是想要伯格回来!也许他就在那棵巨大的西兰花上",
    "Worthless workshop?": "毫无价值的作坊?",
    "Do you want to demolish it?": "你想拆掉它吗?",
    "The wonderful workshop that once brought so much joy to your life, now feels old and empty. This was where your journey started, and all your dreams came true.. Now it's just a worthless pile of crap.": "曾经给你的生活带来许多欢乐的作坊，现在却显得陈旧而空虚。这里是你人生旅程的起点，你所有的梦想都在这里实现。现在它只是一堆毫无价值的垃圾。",
    "Demolish workshop": "拆除作坊",
    "WHOA! The soul of the workshop oozes in your face. A free ghost!": "哇!作坊的灵魂在你的脸上渗出。一个自由的幽灵!",
    "Rest in peace!!!": "安息吧!!",
    "You summon a minor local earthquake, and the workshop explodes violently!": "你召唤一个小地震，作坊剧烈爆炸!",
    "You make a fool of yourself.": "你出洋相了。",
    "He shows you a bruise he got from a fight. He tells you that the other guy also got a bruise.. A way bigger bruise.": "他给你看了打架时留下的瘀伤。他告诉你另一个人也有淤青。一个更大的瘀伤。",
    "He tells you that you need to follow @3DCrede on twitter if you want to be as cool as him.": "他告诉你，如果你想和他一样酷，你需要在推特上关注@3DCrede。",
    "OMG OMG OMG!": "天呐天呐天呐!",
    "Sven": "斯文",
    "Enter the basement": "进入地下室",
    "There is a cosy villa in a clearing. You unlock the door and miraculously squeeze your celestial body through the door. You hear beeping noises from the basement": "空地上有一座舒适的别墅。你打开门，奇迹般地把你的天体挤了进去。你听到从地下室传来的哔哔声",
    "Ultimate Chainsaw Spirit Mk 28": "终极电锯精灵Mk 28",
    "wood/sec": "木头/秒",
    "Sven will cut": "斯文将会砍伐",
    "There is a note on the shack door": "小屋的门上有张纸条",
    "-- Out cutting down all the trees. Will not be back for lunch. Sven --": "——把所有的树都砍掉。不会回来吃午饭了。斯文—-",
    "You hear the buzzing of a non-stop chainsaw in the distance.": "你听到远处电锯不停地嗡嗡作响。",
    "Bye bye trees!": "再见，小树!",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Glittering Skirt": "璀璨半身裙",
    "Worn Pants": "破旧的裤子",
    "Wet Pants": "湿裤子",
    "Bull Diaper": "公牛尿布",
    "Green Pants": "绿色的裤子",
    "Pants Of The Worm God": "虫神的裤子",
    "Pants Of Burger": "伯格裤",
    "Ancient Jerk Pants": "古代牛仔裤",
    "Coco Stained Pants": "可可染色裤",
    "Jerk Pants": "混蛋的裤子",
    "Golden Pants": "金色的裤子",
    "Cat Pants of Ulababula": "乌拉巴布拉的猫裤",
    "Blue Jeans of Karen": "蓝色凯伦牛仔裤",
    "Itchy Pants": "发痒的裤子",
    "Leather Pants": "皮裤",
    "Mega Hand": "超级之手",
    "Lollipop Wand": "棒棒糖棒",
    "Muffin": "松饼",
    "Fist Of The Worm God": "虫神之拳",
    "Worn Glove": "戴过的手套",
    "Cowbar": "牛栏",
    "Claw Of Burger": "伯格之爪",
    "Ancient Jerk Glove": "古拉力手套",
    "Dry Biscuit Glove": "干饼干手套",
    "Confusing Map": "混乱的地图",
    "Broccoli Hands": "西兰花的手",
    "Soft Pillow": "柔软的枕头",
    "Eyes of Regret": "悔恨之眼",
    "Hat of Stardust": "星尘之帽",
    "Yellow Jerk Hair": "黄色乱发",
    "Blue Jerk Hair": "蓝色头发",
    "Purple Jerk Hair": "紫色乱发",
    "Eyes Of The Worm God": "虫神之眼",
    "Sunglasses": "太阳镜",
    "Eyes Of Burger": "伯格之眼",
    "Ancient Jerk Hat": "古代牛仔帽",
    "Leather Cap": "皮革帽",
    "Daves Pot": "戴夫锅",
    "Green Jerk Hair": "绿色头发",
    "Glasses of Chrysitis": "Chrysitis眼镜",
    "Sørens Man Bun": "Sørens男士发髻",
    "Level 3 Helmet": "三级头盔",
    "Third Horn": "第三号角",
    "Melon Glasses": "甜瓜的眼镜",
    "Glittering Skirt)": "璀璨半身裙)",
    "Worn Pants)": "破旧的裤子)",
    "Wet Pants)": "湿裤子)",
    "Bull Diaper)": "公牛尿布)",
    "Green Pants)": "绿色的裤子)",
    "Pants Of The Worm God)": "虫神的裤子)",
    "Pants Of Burger)": "伯格裤)",
    "Ancient Jerk Pants)": "古代牛仔裤)",
    "Coco Stained Pants)": "可可染色裤)",
    "Jerk Pants)": "混蛋的裤子)",
    "Golden Pants)": "金色的裤子)",
    "Cat Pants of Ulababula)": "乌拉巴布拉的猫裤)",
    "Blue Jeans of Karen)": "蓝色凯伦牛仔裤)",
    "Itchy Pants)": "发痒的裤子)",
    "Leather Pants)": "皮裤)",
    "Mega Hand)": "超级之手)",
    "Lollipop Wand)": "棒棒糖棒)",
    "Muffin)": "松饼)",
    "Fist Of The Worm God)": "虫神之拳)",
    "Worn Glove)": "戴过的手套)",
    "Cowbar)": "牛栏)",
    "Claw Of Burger)": "伯格之爪)",
    "Ancient Jerk Glove)": "古拉力手套)",
    "Dry Biscuit Glove)": "干饼干手套)",
    "Confusing Map)": "混乱的地图)",
    "Broccoli Hands)": "西兰花的手)",
    "Soft Pillow)": "柔软的枕头)",
    "Eyes of Regret)": "悔恨之眼)",
    "Hat of Stardust)": "星尘之帽)",
    "Yellow Jerk Hair)": "黄色乱发)",
    "Blue Jerk Hair)": "蓝色头发)",
    "Purple Jerk Hair)": "紫色乱发)",
    "Eyes Of The Worm God)": "虫神之眼)",
    "Sunglasses)": "太阳镜)",
    "Eyes Of Burger)": "伯格之眼)",
    "Ancient Jerk Hat)": "古代牛仔帽)",
    "Leather Cap)": "皮革帽)",
    "Daves Pot)": "戴夫锅)",
    "Green Jerk Hair)": "绿色头发)",
    "Glasses of Chrysitis)": "Chrysitis眼镜)",
    "Sørens Man Bun)": "Sørens男士发髻)",
    "Level 3 Helmet)": "三级头盔)",
    "Third Horn)": "第三号角)",
    "Melon Glasses)": "甜瓜的眼镜)",
    "Chest": "宝箱",
    "Light Weight": "哑铃",
    "Light Weight)": "哑铃)",
    "Thirsty Glasses": "口渴眼镜",
    "Thirsty Glasses)": "口渴眼镜)",
    "Svens Lost Pants": "斯文丢失的裤子",
    "Svens Lost Pants)": "斯文丢失的裤子)",
    "Golden Glove)": "金手套)",
    "Green Glove)": "绿手套)",
    "Axe": "斧子",
    "Axe)": "斧子)",
    "Golden Glove": "金手套",
    "Green Glove": "绿手套",
    "Derek": "德里克",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"黄金: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Head (": "头部 (",
    "Legs (": "腿部 (",
    "Hand (": "手部 (",
    "Chance: ": "几率: ",
    "Uses: ": "使用: ",
    "Use Door of Regret (": "使用 悔恨之门 (",
    "Use Thirsty (": "使用 口渴 (",
    "Use Bull Fart (": "使用 牛屁 (",
    "Drink a health potion (": "喝一口生命药水 (",
    "Browse handheld": "浏览手套",
    "Browse pants": "浏览裤子",
    "Browse headgear": "浏览头饰",
    "": "",
    "(Decent ": "(像样的",
    "(Excellent ": "(卓越的",
    "(Scruffy ": "(邋遢的",
    "(Crazy ": "(疯狂的",
    "Decent ": "像样的",
    "Excellent ": "卓越的",
    "Scruffy ": "邋遢的",
    "Crazy ": "疯狂的",
    "Shhh! Door": "嘘！门",
    "Wood door": "木头之门",
    "Boring door": "无聊的门",
    "Shortcut door": "捷径之门",
    "Gold door": "黄金之门",
    "Coco door": "可可之门",
    "Increases the stardust capacity of your core to ": "增加你核心的星尘容量到 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 黄金"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    " (on)": " (开)",
    " (off)": " (关)",
    "jerk(s) with my strength": "混蛋通过我的力量",
    " risk of detection)": " 被发现的风险)",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^Not yet \((.+) friends\)$/, '还没呢 \($1 个朋友\)'],
    [/^I\'m pretty popular \((.+) friends\)$/, '我很受欢迎 \($1 个朋友\)'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Deposit (.+) coco$/, '放入 $1 可可'],
    [/^Get the gold \(more than (.+) gold\)$/, '获得黄金 \(超过 $1 黄金\)'],
    [/^Get (.+) stardust from Stanley$/, '从斯坦利那里得到 $1 星尘'],
    [/^Derek can heal himself completely (.+) time\(s\) per dungeon$/, '德里克在每个地下城可以治愈自己 $1 次'],
    [/^Feed creature (.+) coco$/, '喂给生物 $1 可可'],
    [/^You get (.+) coco!! Yay$/, '你得到 $1 可可!! 耶'],
    [/^You get (.+) wood!! Yay$/, '你得到 $1 木头!! 耶'],
    [/^You get (.+) gold!!$/, '你得到 $1 黄金!!'],
    [/^You get (.+) stardust!!$/, '你得到 $1 星尘!!'],
    [/^You get (.+) stardust!! Yay$/, '你得到 $1 星尘!! 耶'],
    [/^You get (.+) gold!! Yay$/, '你得到 $1 黄金!! 耶'],
    [/^Heal Derek \((.+) coco\)$/, '治愈德里克 \($1 可可\)'],
    [/^(.+) extra wood from wood doors$/, '$1 额外的木头从木头之门'],
    [/^Sorry, you only have space for (.+) health potions$/, '抱歉，你只能放 $1 生命药水'],
    [/^Derek can search for something healthy to drink (.+) time\(s\) per dungeon. He has a (.+) chance of finding anything$/, '德里克在每个地下城可以搜索生命药水 $1 次。他有 $2 的几率找到任何线索'],
    [/^Derek can totally regret entering a door (.+) time\(s\) per dungeon$/, '在每个地牢中，德里克可以后悔进入一扇门 $1 次'],
    [/^Derek can fart (.+) time\(s\) per dungeon$/, '德里克每个地牢可以放 $1 次屁'],
    [/^it heals like (.+) health.. You have (.+) potions$/, '治疗效果相当于 $1 生命值…你有 $2 药水'],
    [/^Fill potion belt \((.+) gold\)$/, '填满药水腰带 \($1黄金\)'],
    [/^Burger will have a (.+) chance of mining (.+) gold\/sec$/, '伯格将有 $1 的几率开采 $2 黄金\/秒'],
    [/^Will suck (.+) coco\/sec$/, '将会吮吸 $1 可可\/秒'],
    [/^Sucks up (.+) coco\/sec$/, '吮吸 $1 可可\/秒'],
    [/^Burger will chop (.+) wood\/sec$/, '伯格将会砍伐 $1 木头\/秒'],
	[/^level ([\d\.]+)\/([\d\.]+)$/, '等级 $1\/$2'],
	[/^([\d\.]+)\/([\d\.]+) potions$/, '$1\/$2 药水'],
	[/^([\d\.]+)\/([\d\.]+) health$/, '$1\/$2 生命值'],
	[/^([\d\.]+)\/([\d\.]+) stardust$/, '$1\/$2 星尘'],
	[/^([\d\.]+)\/([\d\.]+) health potions!$/, '$1\/$2 生命药水！'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)\% chance$/, '$1]\% 几率'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) coco\/sec$/, '$1 可可\/秒'],
    [/^([\d\.,]+) gold\/sec$/, '$1 黄金\/秒'],
    [/^([\d\.,]+) wood\/sec$/, '$1 木头\/秒'],
    [/^\+([\d\.,]+) extra Thirsty uses$/, '\+$1 额外的口渴使用次数'],
    [/^\+([\d\.,]+) potion healing$/, '\+$1 治疗效果'],
    [/^\+([\d\.,]+) armor$/, '\+$1 护甲'],
    [/^\+([\d\.,]+) strength$/, '\+$1 力量'],
    [/^\+([\d\.,]+) health$/, '\+$1 生命值'],
    [/^\+([\d\.,]+) extra Bull Fart uses$/, '\+$1 额外的牛屁使用次数'],
    [/^\+([\d\.,]+) extra Full Heal uses$/, '\+$1 额外的满血使用次数'],
    [/^\+([\d\.,]+) extra Door of Regret uses$/, '\+$1 额外的悔恨之门使用次数'],
    [/^\+([\d\.,]+) health regeneration per dungeon level$/, '\+$1 生命回复每个地牢等级'],
    [/^([\d\.,]+)\% extra gold from gold doors$/, '$1\% 额外的黄金从黄金之门'],
    [/^\+([\d\.,]+)\% chance of Bull Fart$/, '\+$1\% 牛屁几率'],
    [/^\+([\d\.,]+)\% chance of chest door$/, '\+$1\% 宝箱之门几率'],
    [/^\+([\d\.,]+)\% chance of Thirsty$/, '\+$1\% 几率口渴'],
    [/^\+([\d\.,]+)\% extra stardust from stardust doors$/, '\+$1\% 额外的星尘从星尘之门'],
    [/^\+([\d\.,]+)\% extra gold from gold doors$/, '\+$1\% 额外的黄金从黄金之门'],
    [/^\+([\d\.,]+)\% extra coco from coco doors$/, '\+$1\% 额外的可可从可可之门'],
    [/^([\d\.,]+)\% extra coco from coco doors$/, '$1\% 额外的可可从可可之门'],
    [/^([\d\.,]+) health$/, '$1 生命值'],
    [/^([\d\.,]+) coco per second$/, '$1 可可每秒'],
    [/^([\d\.,]+) stardust$/, '$1 星尘'],
    [/^([\d\.,]+) stardust.$/, '$1 星尘。'],
    [/^([\d\.,]+) jerks$/, '$1 混蛋'],
    [/^([\d\.,]+) ghost\(s\)$/, '$1 幽灵'],
    [/^([\d\.,]+) coin\(s\)$/, '$1 金币'],
    [/^([\d\.,]+) gold$/, '$1 黄金'],
    [/^([\d\.,]+) coco$/, '$1 可可'],
    [/^([\d\.,]+) jerk\(s\) with my armor$/, '$1 混蛋通过护甲'],
    [/^([\d\.,]+) \+ ([\d\.,]+) coco$/, '$1 \+ $2 可可'],
    [/^([\d\.,]+) \+ ([\d\.,]+) gold$/, '$1 \+ $2 黄金'],
    [/^([\d\.,]+) \+ ([\d\.,]+) wood$/, '$1 \+ $2 木头'],
    [/^([\d\.,]+) damage$/, '$1 伤害'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Buy 1 phone coin \(([\d\.,]+) ghost\)$/, '购买 1 电话币 \($1 幽灵\)'],
    [/^Hire Lil\' Gnomey \(([\d\.,]+) stardust\)$/, '雇佣小矮人 \($1 星尘\)'],
    [/^Hire Cat Paws Calvin \(([\d\.,]+) stardust\)$/, '雇佣猫爪加尔文 \($1 星尘\)'],
    [/^Hire Tip Toe Tyler \(([\d\.,]+) stardust\)$/, '雇佣泰勒 \($1 星尘\)'],
    [/^Buy a ghost \(([\d\.,]+) gold\)$/, '购买幽灵 \($1 黄金\)'],
    [/^Stupid number \(([\d\.,]+) coins\)$/, '愚蠢数字 \($1 金币\)'],
    [/^Unknown number \(([\d\.,]+) coin\)$/, '未知数字 \($1 金币\)'],
    [/^Sell \(([\d\.,]+) gold\)$/, '出售 \($1 黄金\)'],
    [/^Sell all \(([\d\.,]+) gold\)$/, '全部出售 \($1 黄金\)'],
    [/^\(([\d\.,]+) gold\)$/, '\($1 黄金\)'],
    [/^\(([\d\.,]+) stardust\)$/, '\($1 星尘\)'],
    [/^\(gain ([\d\.,]+) stardust\)$/, '\(获得 $1 星尘\)'],
    [/^\(([\d\.,]+) wood$/, '\($1 木头'],
    [/^\((.+)\% chance$/, '\($1\% 几率'],
    [/^\+([\d\.,]+)\/s$/, '\+$1\/秒'],
    [/^Bull Fart ([\d\.,]+)$/, '牛屁 $1'],
    [/^Door of Regret ([\d\.,]+)$/, '悔恨之门 $1'],
    [/^level ([\d\.,]+)$/, '等级 $1'],
    [/^Thirsty ([\d\.,]+)$/, '口渴 $1'],
    [/^Full Heal ([\d\.,]+)$/, '满血 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);